# Generated by Django 3.2 on 2022-12-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('country', models.CharField(max_length=254)),
                ('bio', models.CharField(max_length=254)),
                ('known_for', models.CharField(max_length=254)),
            ],
        ),
    ]
