# Generated by Django 3.2 on 2022-12-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image_url',
            field=models.CharField(default='bob', max_length=254),
            preserve_default=False,
        ),
    ]
