# Generated by Django 3.2 on 2023-03-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bugreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('description', models.CharField(max_length=254)),
                ('browser', models.CharField(max_length=254)),
                ('os', models.CharField(max_length=254)),
                ('resolution', models.CharField(max_length=254)),
            ],
        ),
    ]
