# Generated by Django 3.2 on 2023-03-25 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugreport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugreport',
            old_name='resolution',
            new_name='email',
        ),
    ]
